version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: v1-deps-{{ checksum "setup.py" }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements
      - save_cache:
          key: v1-deps-{{ checksum "setup.py" }}
          paths:
            - ".venv"
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            make debug_pytest
            codecov
  publish:
    docker:
      - image: circleci/python:3.5.5
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements
            make publish
  flake8:
    docker:
    - image: circleci/python:3.6.6
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Run flake8
        command: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install flake8
          flake8 . --exclude=migrations,.venv

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - flake8
      - publish:
          requires:
            - test
            - flake8
          filters:
            branches:
              only: master
